services:
  flask:
    build: ./app
    container_name: flask
    networks:
      - 5f063e85-93db-481e-bf1e-b55a047922b5
    ports:
      - 80

  fastapi:
    build: ./api
    container_name: fastapi
    networks:
      - 5f063e85-93db-481e-bf1e-b55a047922b5
    ports:
      - 80

networks:
  5f063e85-93db-481e-bf1e-b55a047922b5:
    name: 5f063e85-93db-481e-bf1e-b55a047922b5
    driver: bridge