[supervisord]
nodaemon=true
logfile=/home/user/logs/supervisord.log


[program:app]
command=./.local/bin/gunicorn -c app/gunicorn.conf.py app.main:app
directory=/home/user
user=user
autostart=true
autorestart=true
redirect_stderr=false
stdout_logfile=/home/user/logs/chatbotplui_stdout.log
stderr_logfile=/home/user/logs/chatbotplui_stderr.log

