[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log


[program:app]
command=./.local/bin/hypercorn -c app/hypercorn.toml app/main:app
directory=/home/user
user=user
autostart=true
autorestart=true
redirect_stderr=false
stdout_logfile=/var/log/hypercorn/access.log
stderr_logfile=/var/log/hypercorn/error.log

