[supervisord]
nodaemon=true
logfile=/home/user/logs/supervisord.log


[program:app]
command=./.local/bin/hypercorn -c api/hypercorn.toml api/main:app
directory=/home/user
user=user
autostart=true
autorestart=true
redirect_stderr=false
stdout_logfile=/home/user/logs/flask.log
stderr_logfile=/home/user/logs/flask_error.log

